server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /api/configgerion
      exposure:
        include: bus-refresh,health,info

spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  main:
    allow-bean-definition-overriding: true
  datasource:
    sqlScriptEncoding: UTF-8
  profiles:
    active: prod
